# Generated by Django 5.0.7 on 2024-07-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diretores_produtoras_rename_categoria_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('ano', models.IntegerField()),
                ('pais', models.TextField()),
                ('categoria', models.ManyToManyField(to='core.categorias')),
                ('diretor', models.ManyToManyField(to='core.diretores')),
                ('produtora', models.ManyToManyField(to='core.produtoras')),
            ],
        ),
    ]
